version: v1

workflows:
  - name: data-onyx-danger
    template: danger-pipeline-v1
    on:
      github:
        pull_request:
          branches: [main]
          types: [opened, synchronize, reopened, ready_for_review, edited]
        push: null
    paths:
      - "**"
